package kriollo.generator.utils

import kriollo.KriolloVersion

open class BaseModel {
    fun javaWarning() = getWarning("//")
    fun bashWarning() = getWarning("#")

    private fun getWarning(commentStyle: String = "//"): String {
        return """
            $commentStyle /!\ Warning
            $commentStyle This file is generated by Kriollo, do not edit it manually 
        """.trimIndent()
    }

    val generatedBy: String = "Generated by Kriollo v${KriolloVersion.VERSION}"

    fun generatedAnnotationImport() = "import javax.annotation.processing.Generated"
    fun generatedAnnotation() = "@Generated(\"$generatedBy\")"
}
