package kriollo.generator.components

import kriollo.Kriollo

open class BaseComponentModel {
    val warning: String = """
        // /!\ Warning
        // This file is generated by Kriollo, do not edit it manually 
    """.trimIndent()

    val generatedBy: String = "Generated by Kriollo v${Kriollo.version}"
}
