package kriollo.generator.templating.jte

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import kriollo.configuration.CodegenConfiguration
import kriollo.generator.CodegenModule
import kriollo.generator.Generator
import kriollo.generator.utils.ServiceProvider
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v0.1.0")
class JteModule(
    configuration: CodegenConfiguration,
    val serviceProvider: ServiceProvider,
) : CodegenModule(configuration) {

    override fun isActivated(): Boolean = configuration.templating.jte.enabled

    override fun provideGenerators(): List<Generator> = listOf(
        JteDirectoryGenerator(configuration),
        JteRootFileGenerator(configuration),
    )

    override fun provideExtensions(generator: Generator) {
        generator.registerExtension(JteJavaDependenciesExtension(configuration, serviceProvider))
        generator.registerExtension(JteMavenPluginExtension(configuration, serviceProvider))
    }
}