package kriollo.generator

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import kriollo.configuration.CodegenConfiguration
import kriollo.generator.nix.NixModule
import kriollo.generator.script.build.BuildScriptModule
import kriollo.generator.maven.MavenModule
import kriollo.generator.git.GitModule
import kriollo.generator.jetbrains.JetbrainsModule
import kriollo.generator.cli.CliModule
import kriollo.generator.cli.script.MainScriptModule
import kriollo.generator.java.JavaModule
import kriollo.generator.kotlin.KotlinModule
import kriollo.generator.templating.jte.JteModule
import kriollo.generator.project.ProjectModule
import kriollo.generator.test.TestsModule
import kriollo.generator.libs.LibrariesModule
import kriollo.generator.utils.ServiceProvider
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v0.1.0")
class CoreModules {
    fun getModules(configuration: CodegenConfiguration, serviceProvider: ServiceProvider): List<CodegenModule> {
        return listOf(
            NixModule(configuration, serviceProvider),
            BuildScriptModule(configuration, serviceProvider),
            MavenModule(configuration, serviceProvider),
            GitModule(configuration, serviceProvider),
            JetbrainsModule(configuration, serviceProvider),
            CliModule(configuration, serviceProvider),
            MainScriptModule(configuration, serviceProvider),
            JavaModule(configuration, serviceProvider),
            KotlinModule(configuration, serviceProvider),
            JteModule(configuration, serviceProvider),
            ProjectModule(configuration, serviceProvider),
            TestsModule(configuration, serviceProvider),
            LibrariesModule(configuration, serviceProvider),
        )
    }
}