package kriollo.generator

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import kriollo.generator.git.GitIgnoreExtension
import kriollo.generator.java.JavaDependencyExtension
import kriollo.generator.maven.MavenArtifactExtension
import kriollo.generator.maven.MavenBomExtension
import kriollo.generator.maven.MavenPluginExtension
import kriollo.generator.maven.MavenPropertiesExtension
import kriollo.generator.nix.DefaultNixFileExtension
import kriollo.services.provider.ServiceProvider
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v2014.0.0")
abstract class Generator {

    abstract fun execute(serviceProvider: ServiceProvider)

    open fun registerExtension(extension: DefaultNixFileExtension) {
        // Left empty for child classes to implement if needed
    }
    open fun registerExtension(extension: MavenPropertiesExtension) {
        // Left empty for child classes to implement if needed
    }
    open fun registerExtension(extension: MavenPluginExtension) {
        // Left empty for child classes to implement if needed
    }
    open fun registerExtension(extension: MavenBomExtension) {
        // Left empty for child classes to implement if needed
    }
    open fun registerExtension(extension: MavenArtifactExtension) {
        // Left empty for child classes to implement if needed
    }
    open fun registerExtension(extension: GitIgnoreExtension) {
        // Left empty for child classes to implement if needed
    }
    open fun registerExtension(extension: JavaDependencyExtension) {
        // Left empty for child classes to implement if needed
    }
}
