package kriollo.generator.maven

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import kriollo.generator.CodegenExtension
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v2024.0.0")
fun interface MavenPluginExtension: CodegenExtension<String>