package kriollo.generator.maven

import kriollo.configuration.CodegenConfiguration
import kriollo.configuration.JavaArtifact
import kriollo.generator.utils.createDirectories
import kriollo.generator.utils.initFile

fun initMaven(configuration: CodegenConfiguration) {
    createPomFile(configuration)
    createDirectories(
        "./src/main/kotlin",
        "./src/test/kotlin",
    )
}

fun createPomFile(configuration: CodegenConfiguration) {
    val dependencies = findDependencies(configuration).joinToString { generateDependency(it) }

    val pomTemplate = """
        <?xml version="1.0" encoding="UTF-8"?>
        <project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
                 xmlns="http://maven.apache.org/POM/4.0.0"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <!-- 
                /!\ Warning  
                This file is generated by Kriollo, do not edit it manually 
            -->
            <modelVersion>4.0.0</modelVersion>
            <groupId>kriollo</groupId>
            <artifactId>kriollo</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <packaging>jar</packaging>
            
            <properties>
                <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                <kotlin.code.style>official</kotlin.code.style>
                <kotlin.compiler.jvmTarget>1.8</kotlin.compiler.jvmTarget>
            </properties>
            
            <build>
                <finalName>kriollo</finalName>
                <sourceDirectory>src/main/kotlin</sourceDirectory>
                <testSourceDirectory>src/test/kotlin</testSourceDirectory>
                <plugins>
                    <plugin>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-plugin</artifactId>
                        <version>1.9.21</version>
                        <executions>
                            <execution>
                                <id>compile</id>
                                <phase>compile</phase>
                                <goals>
                                    <goal>compile</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>test-compile</id>
                                <phase>test-compile</phase>
                                <goals>
                                    <goal>test-compile</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            
            <dependencies>
                <dependency>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib</artifactId>
                    <version>1.9.21</version>
                </dependency>
                $dependencies
            </dependencies>
        </project>
    """.trimIndent()

    initFile("pom.xml", pomTemplate)
}

fun findDependencies(configuration: CodegenConfiguration): List<JavaArtifact> {
    return buildList {
        val jte = configuration.templating.jte
        if(jte.enabled) {
            add(jte.getArtifact())
        }
    }
}

fun generateDependency(javaArtifact: JavaArtifact): String {
    return """
       <dependency>
            <groupId>${javaArtifact.groupId}</groupId>
            <artifactId>${javaArtifact.artifactId}</artifactId>
            <version>${javaArtifact.version}</version>
        </dependency> 
    """.trimIndent()
}
