package kriollo.generator.maven

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import kriollo.generator.CodegenExtension
import kriollo.generator.java.JavaArtifact
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v0.1.0")
fun interface MavenBomExtension: CodegenExtension<JavaArtifact>