# /!\ Warning
# This file is generated by Kriollo, do not edit it manually 

with (import <nixpkgs> {});
mkShell {
    buildInputs = [
        maven
        jdk21
        kotlin
    ];
    shellHook = ''
        export JAVA_HOME=${jdk21.home}
    '';
}