import java.io.File
import java.io.FileWriter
import kotlin.io.path.Path
import kotlin.io.path.createDirectory
import kotlin.io.path.createParentDirectories
import kotlin.io.path.notExists

fun main(args: Array<String>) {

    println(
        """
        Welcome to Kriollo
    """.trimIndent()
    )

    if (args.isEmpty()) {
        println(
            """
        
            Usage : 
                init-project : Init the project structure
            
        """.trimIndent()
        )
        return
    }

    if (args[0] == "init-project") {
        initNixFile()
        initMaven()
        return
    }
}

fun initNixFile() {
    println("> Generating default.nix file")

    val nixTemplate = """
        # /!\ Warning
        # This file is generated by Kriollo, do not edit it manually
        with (import <nixpkgs> {});
        mkShell {
            buildInputs = [
                jdk21
                kotlin
                maven
            ];
            shellHook = ''
              export JAVA_HOME=${'$'}{jdk21.home}
            '';
        }

    """.trimIndent()

    val nixFile = File("default.nix")
    if (!nixFile.exists()) {
        nixFile.createNewFile()
    }

    val fileWriter = FileWriter(nixFile)
    fileWriter.write(nixTemplate)
    fileWriter.flush()
    fileWriter.close()
}

fun initMaven() {
    createPomFile()
    createDirectories()
}

fun createPomFile() {
    println("> Generating pom.xml file")

    val pomTemplate = """
        <?xml version="1.0" encoding="UTF-8"?>
        <project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
                 xmlns="http://maven.apache.org/POM/4.0.0"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <!-- 
                /!\ Warning  
                This file is generated by Kriollo, do not edit it manually 
            -->
            <modelVersion>4.0.0</modelVersion>
            <groupId>kriollo</groupId>
            <artifactId>kriollo</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </project>
    """.trimIndent()

    val pomFile = File("pom.xml")
    if (!pomFile.exists()) {
        pomFile.createNewFile()
    }

    val fileWriter = FileWriter(pomFile)
    fileWriter.write(pomTemplate)
    fileWriter.flush()
    fileWriter.close()
}

fun createDirectories() {
    val paths = listOf("./src/main/kotlin")

    paths.forEach {
        println("> Generating directory $it")
    }

    paths
        .map { Path(it) }
        .filter { it.notExists() }
        .forEach {
            it.createParentDirectories()
            it.createDirectory()
        }

}
