package kriollo.generator.nix

import kriollo.configuration.CodegenConfiguration
import kriollo.generator.base.FileGenerator
import kriollo.generator.utils.ServiceProvider

class DefaultNixFileGenerator(val configuration: CodegenConfiguration) : FileGenerator() {

    override fun isActivated(configuration: CodegenConfiguration): Boolean {
        return configuration.nix.enabled
    }

    override fun getFilePath(configuration: CodegenConfiguration): String = "default.nix"

    override fun getContent(configuration: CodegenConfiguration, serviceProvider: ServiceProvider): String =
        """
            # /!\ Warning
            # This file is generated by Kriollo, do not edit it manually
            with (import <nixpkgs> {});
            mkShell {
                buildInputs = [
                    jdk21
                    kotlin
                    maven
                ];
                shellHook = ''
                  export JAVA_HOME=${'$'}{jdk21.home}
                '';
            }
        """.trimIndent()
}
