package kriollo.generator.nix

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import kriollo.generator.CodegenExtension
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v2024.1.0")
fun interface DefaultNixFileExtension: CodegenExtension<DefaultNixPartial>