package com.gitlab.mbarberot.kriollo.generator.git

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import com.gitlab.mbarberot.kriollo.generator.CodegenExtension
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v2024.2.1")
fun interface GitIgnoreExtension: CodegenExtension<GitIgnoreRules>