package com.gitlab.mbarberot.kriollo.generator.git

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import com.gitlab.mbarberot.kriollo.generator.CodegenModule
import com.gitlab.mbarberot.kriollo.generator.Generator
import com.gitlab.mbarberot.kriollo.services.provider.ServiceProvider
import com.gitlab.mbarberot.kriollo.kriollo.Generated

@Generated("Generated by Kriollo")
class GitModule(
    val serviceProvider: ServiceProvider,
) : CodegenModule() {

    override fun isActivated(): Boolean = serviceProvider.configuration.git.enabled

    override fun provideGenerators(): List<Generator> = listOf(
        GitIgnoreFileGenerator(serviceProvider),
    )

    override fun provideExtensions(generator: Generator) {
        generator.registerExtension(CustomGitIgnoreExtension(serviceProvider))
    }
}