package kriollo.generator.kotlin

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import kriollo.configuration.CodegenConfiguration
import kriollo.generator.CodegenModule
import kriollo.generator.Generator
import kriollo.services.provider.ServiceProvider
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v0.1.0")
class KotlinModule(
    configuration: CodegenConfiguration,
    val serviceProvider: ServiceProvider,
) : CodegenModule(configuration) {

    override fun isActivated(): Boolean = configuration.kotlin.enabled

    override fun provideGenerators(): List<Generator> = listOf(
        KotlinSourceDirectoryGenerator(configuration),
        KotlinTestDirectoryGenerator(configuration),
    )

    override fun provideExtensions(generator: Generator) {
        generator.registerExtension(KotlinJavaDependenciesExtension(configuration, serviceProvider))
        generator.registerExtension(KotlinMavenPluginExtension(configuration, serviceProvider))
        generator.registerExtension(KotlinMavenPropertiesExtension(configuration, serviceProvider))
        generator.registerExtension(KotlinDefaultNixExtension(configuration, serviceProvider))
    }
}