package com.gitlab.mbarberot.kriollo.generator.libs

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import com.gitlab.mbarberot.kriollo.generator.CodegenModule
import com.gitlab.mbarberot.kriollo.generator.Generator
import com.gitlab.mbarberot.kriollo.services.provider.ServiceProvider
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo")
class LibrariesModule(
    val serviceProvider: ServiceProvider,
) : CodegenModule() {

    override fun isActivated(): Boolean = true

    override fun provideGenerators(): List<Generator> = listOf(
    )

    override fun provideExtensions(generator: Generator) {
        generator.registerExtension(JacksonJavaDependenciesExtension(serviceProvider))
        generator.registerExtension(PicocliJavaDependenciesExtension(serviceProvider))
        generator.registerExtension(FeignJavaDependenciesExtension(serviceProvider))
    }
}