package kriollo.generator.script

import kriollo.configuration.CodegenConfiguration
import kriollo.generator.utils.createDirectories
import kriollo.generator.utils.initFile

fun initMainScript(configuration: CodegenConfiguration) {
    val mainClass = configuration.project.mainClass

    val mainScriptTemplate = """
        #!/usr/bin/env bash
        
        # /!\ Warning
        # This file is generated by Kriollo, do not edit it manually 
        
        kotlin -classpath codegen/kriollo.jar $mainClass ${'$'}*
    """.trimIndent()

    createDirectories("./codegen")
    initFile("./codegen/kriollo", mainScriptTemplate, isScript = true)
}