package kriollo.generator.git

import kriollo.generator.utils.initFile

fun initGit() {
    val gitignoreTemplate = """
        # /!\ Warning
        # This file is generated by Kriollo, do not edit it manually 
        
        # Intellij files
        .idea/
        
        # Java artifacts
        *.jar
        
        # Maven working directories
        target/
    """.trimIndent()
    initFile(".gitignore", gitignoreTemplate)
}