package kriollo.generator.git

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import kriollo.generator.CodegenExtension
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v0.1.0")
fun interface GitIgnoreExtension: CodegenExtension<GitIgnoreRules>