package kriollo.generator.git

import kriollo.configuration.CodegenConfiguration
import kriollo.generator.base.FileGenerator
import kriollo.generator.utils.ServiceProvider

class GitIgnoreFileGenerator(val configuration: CodegenConfiguration) : FileGenerator() {

    override fun isActivated(configuration: CodegenConfiguration): Boolean {
        return configuration.git.enabled
    }

    override fun getContent(configuration: CodegenConfiguration, serviceProvider: ServiceProvider) =
        """
            # /!\ Warning
            # This file is generated by Kriollo, do not edit it manually 
            
            # Intellij files
            .idea/
            
            # Java artifacts
            *.jar
            
            # Maven working directories
            target/
        """.trimIndent()

    override fun getFilePath(configuration: CodegenConfiguration) = ".gitignore"
}