cli.enabled = true
java.enabled = true
kotlin.enabled = true
nix.enabled = true
jetbrains.enabled = true
git.enabled = true
scripts.enabled = true
scripts.tests.enabled = true
maven.enabled = true
tests.enabled = true
tests.junit.enabled = true
templating.enabled = true

[project]
groupId = "kriollo"
name = "kriollo"
version = "2024.0.0"
mainClass = "kriollo.KriolloKt"
encoding = "UTF-8"
dependencies = [
    { groupId = "info.picocli", artifactId = "picocli", version = "4.7.6" },
]

[kriollo]
dir = "codegen"

[cli.script]
enabled = true
fileName = "kriollo"
targetDirectory = "codegen"

[scripts.build]
enabled = true
customSteps = [
    { name = "Copy jar into codegen dir", command = "cp target/kriollo.jar codegen/" },
]

[templating.jte]
enabled = true
contentType = "Plain"

[libs.jackson]
dataformats = ["toml"]

[components]

[[components.kriollo]]
path = "kriollo/generator/nix"
name = "nix"
tag = "core"
activationKey = "nix.enabled"
generators = [
    { name = "DefaultNixFileGenerator" },
]
provideExtensions = [
    { name = "DefaultNixFileExtension", provideType = "DefaultNixPartial" },
]


[[components.kriollo]]
path = "kriollo/generator/scripts/build"
name = "BuildScript"
tag = "core"
activationKey = "scripts.build.enabled"
generators = [
    { name = "BuildScriptGenerator" },
]

[[components.kriollo]]
path = "kriollo/generator/scripts"
name = "Scripts"
tag = "core"
activationKey = "scripts.enabled"
generators = [
    { name = "ScriptsDirectoryGenerator" }
]

[[components.kriollo]]
path = "kriollo/generator/scripts/test"
name = "TestScript"
tag = "core"
activationKey = "scripts.tests.enabled"
generators = [
    { name = "TestScriptGenerator" }
]

[[components.kriollo]]
path = "kriollo/generator/maven"
name = "Maven"
tag = "core"
activationKey = "maven.enabled"
generators = [
    { name = "MavenPomGenerator" }
]
extensions = [
    { name = "MavenGitIgnoreExtension" },
    { name = "MavenDefaultNixExtension" },
]
provideExtensions = [
    { name = "MavenPropertiesExtension", provideType = "Pair<String,String>" },
    { name = "MavenPluginExtension", provideType = "String" },
    { name = "MavenBomExtension", provideType = "kriollo.generator.java.JavaArtifact" },
    { name = "MavenArtifactExtension", provideType = "kriollo.generator.java.JavaArtifact" },
]

[[components.kriollo]]
path = "kriollo/generator/git"
name = "Git"
tag = "core"
activationKey = "git.enabled"
generators = [
    { name = "GitIgnoreFileGenerator" }
]
provideExtensions = [
    { name = "GitIgnoreExtension", provideType = "GitIgnoreRules" }
]

[[components.kriollo]]
path = "kriollo/generator/jetbrains"
name = "Jetbrains"
tag = "core"
activationKey = "jetbrains.enabled"
extensions = [
    { name = "JetbrainsGitIgnoreExtension" }
]

[[components.kriollo]]
path = "kriollo/generator/cli"
name = "cli"
tag = "core"
activationKey = "cli.enabled"
extensions = [
    { name = "CliMavenPluginExtension" }
]

[[components.kriollo]]
path = "kriollo/generator/cli/script"
name = "MainScript"
tag = "core"
activationKey = "cli.script.enabled"
generators = [
    { name = "MainScriptDirectoryGenerator" },
    { name = "MainScriptFileGenerator" },
]

[[components.kriollo]]
path = "kriollo/generator/java"
name = "Java"
tag = "core"
activationKey = "java.enabled"
extensions = [
    { name = "JavaGitIgnoreExtension" },
    { name = "JavaNixDefaultExtension" },
]
provideExtensions = [
    { name = "JavaDependencyExtension", provideType = "JavaArtifact" },
]

[[components.kriollo]]
path = "kriollo/generator/kotlin"
name = "Kotlin"
tag = "core"
activationKey = "kotlin.enabled"
generators = [
    { name = "KotlinSourceDirectoryGenerator" },
    { name = "KotlinTestDirectoryGenerator" },
]
extensions = [
    { name = "KotlinJavaDependenciesExtension" },
    { name = "KotlinMavenPluginExtension" },
    { name = "KotlinMavenPropertiesExtension" },
    { name = "KotlinDefaultNixExtension" },
]

[[components.kriollo]]
path = "kriollo/generator/templating/jte"
name = "Jte"
tag = "core"
activationKey = "templating.jte.enabled"
generators = [
    { name = "JteDirectoryGenerator" },
    { name = "JteRootFileGenerator" },
]
extensions = [
    { name = "JteJavaDependenciesExtension" },
    { name = "JteMavenPluginExtension" },
]

[[components.kriollo]]
path = "kriollo/generator/project"
name = "Project"
tag = "core"
activationKey = "-"
generators = [
    { name = "ProjectVersionGenerator" },
]
extensions = [
    { name = "ProjectJavaDependenciesExtension" },
    { name = "ProjectMavenPropertiesExtension" },
    { name = "ProjectMavenArtifactExtension" },
]

[[components.kriollo]]
path = "kriollo/generator/tests"
name = "tests"
tag = "core"
activationKey = "tests.enabled"
extensions = [
    { name = "SurefireMavenPluginExtension" },
]

[[components.kriollo]]
path = "kriollo/generator/tests/junit"
name = "junit"
tag = "core"
activationKey = "tests.junit.enabled"
extensions = [
    { name = "JUnitJavaDependenciesExtension" },
    { name = "JUnitMavenBomExtension" },
]

[[components.kriollo]]
path = "kriollo/generator/libs"
name = "Libraries"
tag = "core"
activationKey = "-"
extensions = [
    { name = "JacksonJavaDependenciesExtension" }
]

[[components.kriollo]]
path = "kriollo/generator/components/kriollo"
name = "Kriollo"
tag = "kriollo"
activationKey = "components.kriollo.isNotEmpty()"
generators = [
    { name = "KriolloModulesGenerator" },
    { name = "KriolloAggregatorsGenerator" },
    { name = "KriolloExtensionsGenerator" },
    { name = "KriolloBaseGeneratorGenerator" },
]