# [justfile] # TODO : justfile
# enabled = true

# [readme] # TODO : readme
# enabled = true
# title = "Kriollo"
# description = "Insert a short description here"
#
# [readme.sections]
# build = true

# [dockerfile] # TODO : dockerfile
# enable = true 
# baseImage = jdk21-temurin


[project]
mainClass = "kriollo.KriolloKt"
encoding = "UTF-8"
# TODO set finalName here
dependencies = []

[cli]
enabled = true

[cli.script]
enabled = true
fileName = "kriollo"
targetDirectory = "codegen"
jarLocation = "codegen/kriollo.jar" # TODO : get "kriollo.jar" from from project equivalent of maven's build.finalName

[java]
enabled = true
# TODO : setup jdk here

[kotlin]
enabled = true
version = "1.9.24"

[nix]
enabled = true

[git]
enabled = true
# TODO : add pre-commit hook for conventional commits

[scripts.build]
enabled = true
customSteps = [
    { name = "Copy jar into codegen dir", command = "cp target/kriollo.jar codegen/" },
]

[maven]
enabled = true

[templating]
enabled = true

[templating.jte]
enabled = true
version = "3.1.12"
contentType = "Plain"

[libs.jackson]
version = "2.13.0"
dataformats = ["toml"]

[components]

[[components.kriollo]]
path = "kriollo/generator/nix"
name = "nix"
tag = "core"
activationKey = "nix.enabled"
generators = [
    { name = "DefaultNixFileGenerator" },
]

[[components.kriollo]]
path = "kriollo/generator/script/build"
name = "BuildScript"
tag = "core"
activationKey = "scripts.build.enabled"
generators = [
    { name = "BuildScriptDirectoryGenerator" },
    { name = "BuildScriptGenerator" },
]

[[components.kriollo]]
path = "kriollo/generator/maven"
name = "Maven"
tag = "core"
activationKey = "maven.enabled"
generators = [
    { name = "MavenPomGenerator" }
]
extensions = [
    { name = "MavenGitIgnoreExtension" }
]
provideExtensions = [
    { name = "MavenPropertiesExtension", provideType = "Pair<String,String>" },
    { name = "MavenPluginExtension", provideType = "String"},
]

[[components.kriollo]]
path = "kriollo/generator/git"
name = "Git"
tag = "core"
activationKey = "git.enabled"
generators = [
    { name = "GitIgnoreFileGenerator" }
]
provideExtensions = [
    { name = "GitIgnoreExtension", provideType = "kriollo.generator.git.GitIgnoreRules"}
]

[[components.kriollo]]
path = "kriollo/generator/jetbrains"
name = "Jetbrains"
tag = "core"
activationKey = "jetbrains.enabled"
extensions = [
    { name = "JetbrainsGitIgnoreExtension" }
]

[[components.kriollo]]
path = "kriollo/generator/cli"
name = "cli"
tag = "core"
activationKey = "cli.enabled"
extensions = [
    { name = "CliMavenPluginExtension" }
]

[[components.kriollo]]
path = "kriollo/generator/cli/script"
name = "MainScript"
tag = "core"
activationKey = "cli.script.enabled"
generators = [
    { name = "MainScriptDirectoryGenerator" },
    { name = "MainScriptFileGenerator" },
]

[[components.kriollo]]
path = "kriollo/generator/java"
name = "Java"
tag = "core"
activationKey = "java.enabled"
extensions = [
    { name = "JavaGitIgnoreExtension" }
]
provideExtensions = [
    { name = "JavaDependencyExtension", provideType = "kriollo.generator.java.JavaArtifact" }
]

[[components.kriollo]]
path = "kriollo/generator/kotlin"
name = "Kotlin"
tag = "core"
activationKey = "kotlin.enabled"
generators = [
    { name = "KotlinSourceDirectoryGenerator" },
    { name = "KotlinTestDirectoryGenerator" },
]
extensions = [
    { name = "KotlinJavaDependenciesExtension" },
    { name = "KotlinMavenPluginExtension" },
    { name = "KotlinMavenPropertiesExtension" },
]

[[components.kriollo]]
path = "kriollo/generator/templating/jte"
name = "Jte"
tag = "core"
activationKey = "templating.jte.enabled"
generators = [
    { name = "JteDirectoryGenerator" },
    { name = "JteRootFileGenerator" },
]
extensions = [
    { name = "JteJavaDependenciesExtension" },
    { name = "JteMavenPluginExtension" },
]

[[components.kriollo]]
path = "kriollo/generator/project"
name = "Project"
tag = "core"
activationKey = "-"
extensions = [
    { name = "ProjectJavaDependenciesExtension" },
    { name = "ProjectMavenPropertiesExtension" }
]

[[components.kriollo]]
path = "kriollo/generator/libs"
name = "Libraries"
tag = "core"
activationKey = "-"
extensions = [
    { name = "JacksonJavaDependenciesExtension" }
]

[[components.kriollo]]
path = "kriollo/generator/components/kriollo"
name = "Kriollo"
tag = "kriollo"
activationKey = "components.kriollo.isNotEmpty()"
generators = [
    { name = "KriolloModulesGenerator" },
    { name = "KriolloAggregatorsGenerator" },
    { name = "KriolloExtensionsGenerator" },
    { name = "KriolloBaseGeneratorGenerator" },
]

#[[components.kriollo-extensions]]
#path = "kriollo/generator/base/extensions"
#extensions = [
#    { name = "JavaDependencyExtension", provide = "kriollo.generator.java.JavaArtifact" },
#    { name = "GitIgnoreExtension", provide = "kriollo.generator.git.GitIgnoreRules" },
#    { name = "MavenPluginExtension", provide = "String" },
#]