package kriollo

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v2014.0.0-SNAPSHOT")
object KriolloVersion {
    const val VERSION = "2014.0.0-SNAPSHOT"
}