package kriollo

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v2024.1.0")
object KriolloVersion {
    const val VERSION = "2024.1.0"
}