package com.gitlab.mbarberot.kriollo.generator.templating.jte

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import com.gitlab.mbarberot.kriollo.generator.CodegenModule
import com.gitlab.mbarberot.kriollo.generator.Generator
import com.gitlab.mbarberot.kriollo.services.provider.ServiceProvider
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v2024.3.0")
class JteModule(
    val serviceProvider: ServiceProvider,
) : CodegenModule() {

    override fun isActivated(): Boolean = serviceProvider.configuration.project.libs.jte.enabled

    override fun provideGenerators(): List<Generator> = listOf(
        JteDirectoryGenerator(serviceProvider),
        JteRootFileGenerator(serviceProvider),
    )

    override fun provideExtensions(generator: Generator) {
        generator.registerExtension(JteJavaDependenciesExtension(serviceProvider))
        generator.registerExtension(JteMavenPluginExtension(serviceProvider))
    }
}