package com.gitlab.mbarberot.kriollo.generator.utils

open class BaseModel {
    fun javaWarning() = getWarning("//")
    fun bashWarning() = getWarning("#")

    private fun getWarning(commentStyle: String = "//"): String {
        return """
            $commentStyle /!\ Warning
            $commentStyle This file is generated by Kriollo, do not edit it manually 
        """.trimIndent()
    }

    val generatedBy: String = "Generated by Kriollo"

    fun generatedAnnotationImport() = "import com.gitlab.mbarberot.kriollo.Generated"
    fun generatedAnnotation() = "@Generated(\"$generatedBy\")"
}
