package com.gitlab.mbarberot.kriollo.generator.java

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import com.gitlab.mbarberot.kriollo.generator.CodegenExtension
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo")
fun interface JavaDependencyExtension: CodegenExtension<JavaArtifact>