package com.gitlab.mbarberot.kriollo.generator.kotlin

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import com.gitlab.mbarberot.kriollo.generator.CodegenModule
import com.gitlab.mbarberot.kriollo.generator.Generator
import com.gitlab.mbarberot.kriollo.services.provider.ServiceProvider
import com.gitlab.mbarberot.kriollo.kriollo.Generated

@Generated("Generated by Kriollo")
class KotlinModule(
    val serviceProvider: ServiceProvider,
) : CodegenModule() {

    override fun isActivated(): Boolean = serviceProvider.configuration.kotlin.enabled

    override fun provideGenerators(): List<Generator> = listOf(
        KotlinSourceDirectoryGenerator(serviceProvider),
        KotlinTestDirectoryGenerator(serviceProvider),
    )

    override fun provideExtensions(generator: Generator) {
        generator.registerExtension(KotlinJavaDependenciesExtension(serviceProvider))
        generator.registerExtension(KotlinMavenCompilerPluginExtension(serviceProvider))
        generator.registerExtension(KotlinMavenPluginExtension(serviceProvider))
        generator.registerExtension(KotlinMavenPropertiesExtension(serviceProvider))
        generator.registerExtension(KotlinDefaultNixExtension(serviceProvider))
        generator.registerExtension(KotlinGitIgnoreExtension(serviceProvider))
    }
}