package com.gitlab.mbarberot.kriollo.generator.maven

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import com.gitlab.mbarberot.kriollo.generator.CodegenExtension
import com.gitlab.mbarberot.kriollo.kriollo.Generated

@Generated("Generated by Kriollo")
fun interface MavenPropertiesExtension: CodegenExtension<Pair<String,String>>