package com.gitlab.mbarberot.kriollo.generator.maven

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import com.gitlab.mbarberot.kriollo.generator.CodegenExtension
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v2024.3.0")
fun interface MavenPluginExtension: CodegenExtension<String>