package com.gitlab.mbarberot.kriollo.generator

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import com.gitlab.mbarberot.kriollo.generator.git.GitIgnoreExtension
import com.gitlab.mbarberot.kriollo.generator.java.JavaDependencyExtension
import com.gitlab.mbarberot.kriollo.generator.maven.MavenArtifactExtension
import com.gitlab.mbarberot.kriollo.generator.maven.MavenBomExtension
import com.gitlab.mbarberot.kriollo.generator.maven.MavenPluginExtension
import com.gitlab.mbarberot.kriollo.generator.maven.MavenPropertiesExtension
import com.gitlab.mbarberot.kriollo.generator.nix.DefaultNixFileExtension
import com.gitlab.mbarberot.kriollo.services.provider.ServiceProvider
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v2024.2.1")
abstract class Generator {

    abstract fun execute(serviceProvider: ServiceProvider)

    open fun registerExtension(extension: DefaultNixFileExtension) {
        // Left empty for child classes to implement if needed
    }
    open fun registerExtension(extension: MavenPropertiesExtension) {
        // Left empty for child classes to implement if needed
    }
    open fun registerExtension(extension: MavenPluginExtension) {
        // Left empty for child classes to implement if needed
    }
    open fun registerExtension(extension: MavenBomExtension) {
        // Left empty for child classes to implement if needed
    }
    open fun registerExtension(extension: MavenArtifactExtension) {
        // Left empty for child classes to implement if needed
    }
    open fun registerExtension(extension: GitIgnoreExtension) {
        // Left empty for child classes to implement if needed
    }
    open fun registerExtension(extension: JavaDependencyExtension) {
        // Left empty for child classes to implement if needed
    }
}
