package kriollo.generator.components.kriollo

// /!\ Warning
// This file is generated by Kriollo, do not edit it manually 

import kriollo.generator.CodegenModule
import kriollo.generator.Generator
import kriollo.services.provider.ServiceProvider
import javax.annotation.processing.Generated

@Generated("Generated by Kriollo v2014.0.0-SNAPSHOT")
class KriolloModule(
    val serviceProvider: ServiceProvider,
) : CodegenModule() {

    override fun isActivated(): Boolean = serviceProvider.configuration.components.kriollo.isNotEmpty()

    override fun provideGenerators(): List<Generator> = listOf(
        KriolloModulesGenerator(serviceProvider),
        KriolloAggregatorsGenerator(serviceProvider),
        KriolloExtensionsGenerator(serviceProvider),
        KriolloBaseGeneratorGenerator(serviceProvider),
    )

}