package kriollo.generator.cli.script

import kriollo.generator.base.FileGenerator
import kriollo.services.provider.ServiceProvider

class MainScriptFileGenerator(val serviceProvider: ServiceProvider) : FileGenerator() {

    override fun getFilePath(): String {
        val scriptConfiguration = serviceProvider.configuration.cli.script

        return "./${scriptConfiguration.targetDirectory}/${scriptConfiguration.fileName}"
    }

    override fun isScript(): Boolean = true

    override fun getContent(serviceProvider: ServiceProvider): String {
        return """
                #!/usr/bin/env bash
                
                # /!\ Warning
                # This file is generated by Kriollo, do not edit it manually 
                
                java -jar ${serviceProvider.configuration.cli.script.jarLocation} ${'$'}*
            """.trimIndent()
    }
}