package kriollo.generator.cli.script

import kriollo.configuration.CodegenConfiguration
import kriollo.generator.Generator
import kriollo.generator.utils.ServiceProvider

class MainScriptGenerator : Generator {

    override fun isActivated(configuration: CodegenConfiguration): Boolean {
        return configuration.cli.enabled && configuration.cli.script.enabled
    }

    override fun execute(configuration: CodegenConfiguration, serviceProvider: ServiceProvider) {
        val scriptConfiguration = configuration.cli.script

        val targetDirectory = scriptConfiguration.targetDirectory
        val scriptFileName = scriptConfiguration.fileName
        val jarLocation = scriptConfiguration.jarLocation

        val mainScriptTemplate = generateContent(jarLocation)

        serviceProvider.fileSystem.createDirectory("./$targetDirectory")
        serviceProvider.fileSystem.createFile("./$targetDirectory/$scriptFileName", mainScriptTemplate, isScript = true)
    }

    private fun generateContent(jarLocation: String): String {
        val mainScriptTemplate = """
                #!/usr/bin/env bash
                
                # /!\ Warning
                # This file is generated by Kriollo, do not edit it manually 
                
                java -jar $jarLocation ${'$'}*
            """.trimIndent()
        return mainScriptTemplate
    }
}